name: Update Blog Metadata

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "write"

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Workload Identity Federation
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          create_credentials_file: true

      - name: Go Test
        run: go test -v ./...

      - name: Update Metadata
        run: ./build.sh
        env:
          AI_STUDIO_API_KEY: ${{ secrets.AI_STUDIO_API_KEY }}
          PROVIDER: aistudio
          #PROJECT_ID: '${{ secrets.PROJECT_ID }}'
          #LOCATION: us-central1

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "feat(blog): Update blog metadata"
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
